language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
node_js:
  - "node"
script:
  - npm run lint
  - npm run transpile
  - npm test -- --record
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
